# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jordi Pàmies - Software Engineer, Geek & Music lover.

description: Personal Website where I'll write posts releated with Software Engineering, Node.js, Scalability, linux, IoT, Smart Cities, RaspberryPi, or whatever I belive could be useful to read it later.
author:
  name: jpamies
  email: mail@jpamies.com
  github: jpamies
  twitter: jpamies
  pinterest: jpamies
  linkedin: jordipamies
  bio: Jordi Pàmies - Software Engineer, Geek & Music lover
  email_md5: 83967f330bc24097245088a87df7aa8c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
